// -------------------------------------------------------
// Mannat Events — Banquet Menu Library
// Source: Supplied banquet/package PDF documentation
// DO NOT invent items or limits not in the source data.
// -------------------------------------------------------

import type { BanquetPackage } from './types'

// ──────────────────────────────────────────────────────
// VEGETARIAN BANQUET PACKAGES
// ──────────────────────────────────────────────────────

export const VEG_PREMIUM: BanquetPackage = {
  id: 'veg-premium',
  name: 'Premium Veg Banquet',
  mealType: 'veg',
  pricePerHead: 2000,
  tagline: '₹2,000 per head · A rich vegetarian banquet experience',
  categories: [
    {
      id: 'welcome-drinks',
      label: 'Welcome Drinks',
      emoji: '🥤',
      limit: 2,
      items: [
        { name: 'Mango Lassi' },
        { name: 'Rose Sherbat' },
        { name: 'Lemon Mint Cooler' },
        { name: 'Jaljeera' },
        { name: 'Aam Panna' },
        { name: 'Thandai' },
        { name: 'Masala Chach (Buttermilk)' },
        { name: 'Coconut Water' },
      ],
    },
    {
      id: 'starters-veg-indian',
      label: 'Starters — Veg Indian',
      emoji: '🥗',
      limit: 4,
      items: [
        { name: 'Paneer Tikka' },
        { name: 'Hara Bhara Kebab' },
        { name: 'Corn Palak Tikki' },
        { name: 'Dahi Puri Chaat' },
        { name: 'Aloo Tikki Chaat' },
        { name: 'Veg Seekh Kebab' },
        { name: 'Mushroom Tikka' },
        { name: 'Peshwari Paneer Tikka' },
      ],
    },
    {
      id: 'starters-veg-oriental',
      label: 'Starters — Veg Oriental & Western',
      emoji: '🥡',
      limit: 2,
      items: [
        { name: 'Veg Spring Rolls' },
        { name: 'Crispy Corn' },
        { name: 'Veg Manchurian (Dry)' },
        { name: 'Chilli Paneer (Dry)' },
        { name: 'Stuffed Mushroom' },
        { name: 'Bruschetta' },
      ],
    },
    {
      id: 'soup',
      label: 'Soup',
      emoji: '🍲',
      limit: 2,
      items: [
        { name: 'Tomato Shorba' },
        { name: 'Sweet Corn Vegetable Soup' },
        { name: 'Dal Shorba' },
        { name: 'Mulligatawny Soup (Veg)' },
        { name: 'Mushroom Cream Soup' },
        { name: 'Hot & Sour Vegetable Soup' },
      ],
    },
    {
      id: 'salads',
      label: 'Salads',
      emoji: '🥙',
      limit: 4,
      items: [
        { name: 'Green Salad' },
        { name: 'Russian Salad' },
        { name: 'Sprouts Salad' },
        { name: 'Corn Salad' },
        { name: 'Pasta Salad' },
        { name: 'Coleslaw' },
        { name: 'Fruit Salad' },
        { name: 'Papdi Chaat' },
      ],
    },
    {
      id: 'raita-curd',
      label: 'Raita / Curd',
      emoji: '🫙',
      limit: 1,
      items: [
        { name: 'Boondi Raita' },
        { name: 'Mixed Raita' },
        { name: 'Cucumber Raita' },
        { name: 'Plain Curd' },
        { name: 'Pineapple Raita' },
      ],
    },
    {
      id: 'paneer-main',
      label: 'Paneer Main Course',
      emoji: '🧀',
      limit: 2,
      items: [
        { name: 'Paneer Butter Masala' },
        { name: 'Shahi Paneer' },
        { name: 'Kadai Paneer' },
        { name: 'Palak Paneer' },
        { name: 'Paneer Lababdar' },
        { name: 'Paneer Makhani' },
      ],
    },
    {
      id: 'veg-main',
      label: 'Veg Main Course',
      emoji: '🍛',
      limit: 3,
      items: [
        { name: 'Aloo Gobi' },
        { name: 'Veg Kolhapuri' },
        { name: 'Matar Mushroom' },
        { name: 'Bhindi Masala' },
        { name: 'Lauki Kofta' },
        { name: 'Mix Vegetable' },
        { name: 'Dum Aloo' },
        { name: 'Navratan Korma' },
      ],
    },
    {
      id: 'dal',
      label: 'Dal',
      emoji: '🫕',
      limit: 1,
      items: [
        { name: 'Dal Makhani' },
        { name: 'Dal Tadka' },
        { name: 'Dal Fry' },
        { name: 'Panchmel Dal' },
        { name: 'Chana Masala' },
      ],
    },
    {
      id: 'rice-noodles',
      label: 'Rice / Noodles',
      emoji: '🍚',
      limit: 2,
      items: [
        { name: 'Steamed Rice' },
        { name: 'Jeera Rice' },
        { name: 'Veg Pulao' },
        { name: 'Veg Biryani' },
        { name: 'Schezwan Fried Rice' },
        { name: 'Veg Hakka Noodles' },
      ],
    },
    {
      id: 'breads',
      label: 'Breads (Assorted)',
      emoji: '🫓',
      // No limit — assorted breads are served freely
      items: [
        { name: 'Butter Naan' },
        { name: 'Tandoori Roti' },
        { name: 'Laccha Paratha' },
        { name: 'Missi Roti' },
        { name: 'Kulcha' },
      ],
    },
    {
      id: 'desserts',
      label: 'Desserts',
      emoji: '🍮',
      limit: 4,
      items: [
        { name: 'Gulab Jamun' },
        { name: 'Rasgulla' },
        { name: 'Kheer' },
        { name: 'Gajar Halwa' },
        { name: 'Moong Dal Halwa' },
        { name: 'Phirni' },
        { name: 'Jalebi with Rabri' },
        { name: 'Ras Malai' },
        { name: 'Kulfi Falooda' },
      ],
    },
  ],
  liveStations: [
    {
      id: 'tawa',
      label: 'Tawa Tak-A-Tak Station',
      subItems: [
        'Tawa Paneer',
        'Tawa Aloo',
        'Tawa Mushroom',
        'Tawa Gobhi',
      ],
    },
    {
      id: 'chaat',
      label: 'Chaat Corner',
      subItems: [
        'Pani Puri',
        'Sev Puri',
        'Bhel Puri',
        'Dahi Bhalla',
      ],
    },
    {
      id: 'ice-cream',
      label: 'Ice Cream Counter',
      subItems: [
        'Vanilla',
        'Chocolate',
        'Strawberry',
        'Butterscotch',
        'Mango',
      ],
    },
  ],
  addOns: [
    'High Tea (per head surcharge)',
    'Mocktail Bar Setup',
    'Paan Counter',
    'Extra Live Station',
    'Extended Service (per hour)',
  ],
}

export const VEG_EXECUTIVE: BanquetPackage = {
  id: 'veg-executive',
  name: 'Executive Veg Banquet',
  mealType: 'veg',
  pricePerHead: 2500,
  tagline: '₹2,500 per head · A premium vegetarian feast with extra variety',
  categories: [
    {
      id: 'welcome-drinks',
      label: 'Welcome Drinks',
      emoji: '🥤',
      limit: 3,
      items: [
        { name: 'Mango Lassi' },
        { name: 'Rose Sherbat' },
        { name: 'Lemon Mint Cooler' },
        { name: 'Jaljeera' },
        { name: 'Aam Panna' },
        { name: 'Thandai' },
        { name: 'Masala Chach (Buttermilk)' },
        { name: 'Coconut Water' },
        { name: 'Fresh Lime Soda' },
      ],
    },
    {
      id: 'starters-veg-indian',
      label: 'Starters — Veg Indian',
      emoji: '🥗',
      limit: 5,
      items: [
        { name: 'Paneer Tikka' },
        { name: 'Hara Bhara Kebab' },
        { name: 'Corn Palak Tikki' },
        { name: 'Dahi Puri Chaat' },
        { name: 'Aloo Tikki Chaat' },
        { name: 'Veg Seekh Kebab' },
        { name: 'Mushroom Tikka' },
        { name: 'Peshwari Paneer Tikka' },
        { name: 'Dahi Ke Sholay' },
        { name: 'Paneer Malai Tikka' },
      ],
    },
    {
      id: 'starters-veg-oriental',
      label: 'Starters — Veg Oriental & Western',
      emoji: '🥡',
      limit: 3,
      items: [
        { name: 'Veg Spring Rolls' },
        { name: 'Crispy Corn' },
        { name: 'Veg Manchurian (Dry)' },
        { name: 'Chilli Paneer (Dry)' },
        { name: 'Stuffed Mushroom' },
        { name: 'Bruschetta' },
        { name: 'Thai Veg Satay' },
      ],
    },
    {
      id: 'soup',
      label: 'Soup',
      emoji: '🍲',
      limit: 2,
      items: [
        { name: 'Tomato Shorba' },
        { name: 'Sweet Corn Vegetable Soup' },
        { name: 'Dal Shorba' },
        { name: 'Mulligatawny Soup (Veg)' },
        { name: 'Mushroom Cream Soup' },
        { name: 'Hot & Sour Vegetable Soup' },
        { name: 'Lemon Coriander Soup' },
      ],
    },
    {
      id: 'salads',
      label: 'Salads',
      emoji: '🥙',
      limit: 5,
      items: [
        { name: 'Green Salad' },
        { name: 'Russian Salad' },
        { name: 'Sprouts Salad' },
        { name: 'Corn Salad' },
        { name: 'Pasta Salad' },
        { name: 'Coleslaw' },
        { name: 'Fruit Salad' },
        { name: 'Papdi Chaat' },
        { name: 'Greek Salad' },
        { name: 'Thai Salad' },
      ],
    },
    {
      id: 'raita-curd',
      label: 'Raita / Curd',
      emoji: '🫙',
      limit: 1,
      items: [
        { name: 'Boondi Raita' },
        { name: 'Mixed Raita' },
        { name: 'Cucumber Raita' },
        { name: 'Plain Curd' },
        { name: 'Pineapple Raita' },
      ],
    },
    {
      id: 'paneer-main',
      label: 'Paneer Main Course',
      emoji: '🧀',
      limit: 2,
      items: [
        { name: 'Paneer Butter Masala' },
        { name: 'Shahi Paneer' },
        { name: 'Kadai Paneer' },
        { name: 'Palak Paneer' },
        { name: 'Paneer Lababdar' },
        { name: 'Paneer Makhani' },
        { name: 'Paneer Pasanda' },
      ],
    },
    {
      id: 'veg-main',
      label: 'Veg Main Course',
      emoji: '🍛',
      limit: 4,
      items: [
        { name: 'Aloo Gobi' },
        { name: 'Veg Kolhapuri' },
        { name: 'Matar Mushroom' },
        { name: 'Bhindi Masala' },
        { name: 'Lauki Kofta' },
        { name: 'Mix Vegetable' },
        { name: 'Dum Aloo' },
        { name: 'Navratan Korma' },
        { name: 'Tindora Masala' },
        { name: 'Veg Jaipuri' },
      ],
    },
    {
      id: 'dal',
      label: 'Dal',
      emoji: '🫕',
      limit: 1,
      items: [
        { name: 'Dal Makhani' },
        { name: 'Dal Tadka' },
        { name: 'Dal Fry' },
        { name: 'Panchmel Dal' },
        { name: 'Chana Masala' },
        { name: 'Rajma Masala' },
      ],
    },
    {
      id: 'rice-noodles',
      label: 'Rice / Noodles',
      emoji: '🍚',
      limit: 2,
      items: [
        { name: 'Steamed Rice' },
        { name: 'Jeera Rice' },
        { name: 'Veg Pulao' },
        { name: 'Veg Biryani' },
        { name: 'Schezwan Fried Rice' },
        { name: 'Veg Hakka Noodles' },
        { name: 'Kashmiri Pulao' },
      ],
    },
    {
      id: 'breads',
      label: 'Breads (Assorted)',
      emoji: '🫓',
      items: [
        { name: 'Butter Naan' },
        { name: 'Tandoori Roti' },
        { name: 'Laccha Paratha' },
        { name: 'Missi Roti' },
        { name: 'Kulcha' },
        { name: 'Garlic Naan' },
      ],
    },
    {
      id: 'desserts',
      label: 'Desserts',
      emoji: '🍮',
      limit: 5,
      items: [
        { name: 'Gulab Jamun' },
        { name: 'Rasgulla' },
        { name: 'Kheer' },
        { name: 'Gajar Halwa' },
        { name: 'Moong Dal Halwa' },
        { name: 'Phirni' },
        { name: 'Jalebi with Rabri' },
        { name: 'Ras Malai' },
        { name: 'Kulfi Falooda' },
        { name: 'Shahi Tukda' },
      ],
    },
  ],
  liveStations: [
    {
      id: 'tawa',
      label: 'Tawa Tak-A-Tak Station',
      subItems: [
        'Tawa Paneer',
        'Tawa Aloo',
        'Tawa Mushroom',
        'Tawa Gobhi',
      ],
    },
    {
      id: 'chaat',
      label: 'Chaat Corner',
      subItems: [
        'Pani Puri',
        'Sev Puri',
        'Bhel Puri',
        'Dahi Bhalla',
      ],
    },
    {
      id: 'pasta',
      label: 'Pasta & Pizza Station',
      subItems: [
        'Penne Arrabbiata',
        'Mac & Cheese',
        'Margherita Pizza',
      ],
    },
    {
      id: 'ice-cream',
      label: 'Ice Cream Counter',
      subItems: [
        'Vanilla',
        'Chocolate',
        'Strawberry',
        'Butterscotch',
        'Mango',
        'Pista',
      ],
    },
  ],
  addOns: [
    'High Tea (per head surcharge)',
    'Mocktail Bar Setup',
    'Paan Counter',
    'Extra Live Station',
    'Extended Service (per hour)',
    'Fruit Platter Station',
  ],
}

export const VEG_PLATINUM: BanquetPackage = {
  id: 'veg-platinum',
  name: 'Platinum Veg Banquet',
  mealType: 'veg',
  pricePerHead: 3000,
  tagline: '₹3,000 per head · The ultimate luxury vegetarian banquet',
  categories: [
    {
      id: 'welcome-drinks',
      label: 'Welcome Drinks',
      emoji: '🥤',
      limit: 4,
      items: [
        { name: 'Mango Lassi' },
        { name: 'Rose Sherbat' },
        { name: 'Lemon Mint Cooler' },
        { name: 'Jaljeera' },
        { name: 'Aam Panna' },
        { name: 'Thandai' },
        { name: 'Masala Chach (Buttermilk)' },
        { name: 'Coconut Water' },
        { name: 'Fresh Lime Soda' },
        { name: 'Gondhoraj Nimbu Sherbat' },
      ],
    },
    {
      id: 'starters-veg-indian',
      label: 'Starters — Veg Indian',
      emoji: '🥗',
      limit: 6,
      items: [
        { name: 'Paneer Tikka' },
        { name: 'Hara Bhara Kebab' },
        { name: 'Corn Palak Tikki' },
        { name: 'Dahi Puri Chaat' },
        { name: 'Aloo Tikki Chaat' },
        { name: 'Veg Seekh Kebab' },
        { name: 'Mushroom Tikka' },
        { name: 'Peshwari Paneer Tikka' },
        { name: 'Dahi Ke Sholay' },
        { name: 'Paneer Malai Tikka' },
        { name: 'Achari Paneer Tikka' },
        { name: 'Rajasthani Mirchi Vada' },
      ],
    },
    {
      id: 'starters-veg-oriental',
      label: 'Starters — Veg Oriental & Western',
      emoji: '🥡',
      limit: 3,
      items: [
        { name: 'Veg Spring Rolls' },
        { name: 'Crispy Corn' },
        { name: 'Veg Manchurian (Dry)' },
        { name: 'Chilli Paneer (Dry)' },
        { name: 'Stuffed Mushroom' },
        { name: 'Bruschetta' },
        { name: 'Thai Veg Satay' },
        { name: 'Veg Dim Sum' },
      ],
    },
    {
      id: 'soup',
      label: 'Soup',
      emoji: '🍲',
      limit: 2,
      items: [
        { name: 'Tomato Shorba' },
        { name: 'Sweet Corn Vegetable Soup' },
        { name: 'Dal Shorba' },
        { name: 'Mulligatawny Soup (Veg)' },
        { name: 'Mushroom Cream Soup' },
        { name: 'Hot & Sour Vegetable Soup' },
        { name: 'Lemon Coriander Soup' },
        { name: 'Gazpacho (Chilled)' },
      ],
    },
    {
      id: 'salads',
      label: 'Salads',
      emoji: '🥙',
      limit: 6,
      items: [
        { name: 'Green Salad' },
        { name: 'Russian Salad' },
        { name: 'Sprouts Salad' },
        { name: 'Corn Salad' },
        { name: 'Pasta Salad' },
        { name: 'Coleslaw' },
        { name: 'Fruit Salad' },
        { name: 'Papdi Chaat' },
        { name: 'Greek Salad' },
        { name: 'Thai Salad' },
        { name: 'Quinoa Salad' },
      ],
    },
    {
      id: 'raita-curd',
      label: 'Raita / Curd',
      emoji: '🫙',
      limit: 1,
      items: [
        { name: 'Boondi Raita' },
        { name: 'Mixed Raita' },
        { name: 'Cucumber Raita' },
        { name: 'Plain Curd' },
        { name: 'Pineapple Raita' },
      ],
    },
    {
      id: 'paneer-main',
      label: 'Paneer Main Course',
      emoji: '🧀',
      limit: 3,
      items: [
        { name: 'Paneer Butter Masala' },
        { name: 'Shahi Paneer' },
        { name: 'Kadai Paneer' },
        { name: 'Palak Paneer' },
        { name: 'Paneer Lababdar' },
        { name: 'Paneer Makhani' },
        { name: 'Paneer Pasanda' },
        { name: 'Paneer Khurchan' },
      ],
    },
    {
      id: 'veg-main',
      label: 'Veg Main Course',
      emoji: '🍛',
      limit: 4,
      items: [
        { name: 'Aloo Gobi' },
        { name: 'Veg Kolhapuri' },
        { name: 'Matar Mushroom' },
        { name: 'Bhindi Masala' },
        { name: 'Lauki Kofta' },
        { name: 'Mix Vegetable' },
        { name: 'Dum Aloo' },
        { name: 'Navratan Korma' },
        { name: 'Tindora Masala' },
        { name: 'Veg Jaipuri' },
        { name: 'Kathal Masala (Jackfruit)' },
        { name: 'Stuffed Capsicum' },
      ],
    },
    {
      id: 'dal',
      label: 'Dal',
      emoji: '🫕',
      limit: 1,
      items: [
        { name: 'Dal Makhani' },
        { name: 'Dal Tadka' },
        { name: 'Dal Fry' },
        { name: 'Panchmel Dal' },
        { name: 'Chana Masala' },
        { name: 'Rajma Masala' },
        { name: 'Amti Dal' },
      ],
    },
    {
      id: 'rice-noodles',
      label: 'Rice / Noodles',
      emoji: '🍚',
      limit: 2,
      items: [
        { name: 'Steamed Rice' },
        { name: 'Jeera Rice' },
        { name: 'Veg Pulao' },
        { name: 'Veg Biryani' },
        { name: 'Schezwan Fried Rice' },
        { name: 'Veg Hakka Noodles' },
        { name: 'Kashmiri Pulao' },
        { name: 'Zaffrani Rice' },
      ],
    },
    {
      id: 'breads',
      label: 'Breads (Assorted)',
      emoji: '🫓',
      items: [
        { name: 'Butter Naan' },
        { name: 'Tandoori Roti' },
        { name: 'Laccha Paratha' },
        { name: 'Missi Roti' },
        { name: 'Kulcha' },
        { name: 'Garlic Naan' },
        { name: 'Stuffed Naan' },
      ],
    },
    {
      id: 'desserts',
      label: 'Desserts',
      emoji: '🍮',
      limit: 6,
      items: [
        { name: 'Gulab Jamun' },
        { name: 'Rasgulla' },
        { name: 'Kheer' },
        { name: 'Gajar Halwa' },
        { name: 'Moong Dal Halwa' },
        { name: 'Phirni' },
        { name: 'Jalebi with Rabri' },
        { name: 'Ras Malai' },
        { name: 'Kulfi Falooda' },
        { name: 'Shahi Tukda' },
        { name: 'Malpua with Rabri' },
        { name: 'Badam Halwa' },
      ],
    },
  ],
  liveStations: [
    {
      id: 'tawa',
      label: 'Tawa Tak-A-Tak Station',
      subItems: [
        'Tawa Paneer',
        'Tawa Aloo',
        'Tawa Mushroom',
        'Tawa Gobhi',
        'Tawa Mixed Vegetables',
      ],
    },
    {
      id: 'chaat',
      label: 'Chaat Corner',
      subItems: [
        'Pani Puri',
        'Sev Puri',
        'Bhel Puri',
        'Dahi Bhalla',
        'Raj Kachori',
      ],
    },
    {
      id: 'pasta',
      label: 'Pasta & Pizza Station',
      subItems: [
        'Penne Arrabbiata',
        'Mac & Cheese',
        'Spaghetti Aglio e Olio',
        'Margherita Pizza',
        'Veggie Supreme Pizza',
      ],
    },
    {
      id: 'indian-sweets',
      label: 'Live Indian Sweets Counter',
      subItems: [
        'Jalebi (freshly fried)',
        'Gulab Jamun (warm)',
        'Malpua',
      ],
    },
    {
      id: 'ice-cream',
      label: 'Ice Cream & Dessert Counter',
      subItems: [
        'Vanilla',
        'Chocolate',
        'Strawberry',
        'Butterscotch',
        'Mango',
        'Pista',
        'Kulfi (Malai)',
      ],
    },
  ],
  addOns: [
    'High Tea (per head surcharge)',
    'Mocktail Bar Setup',
    'Paan Counter',
    'Extra Live Station',
    'Extended Service (per hour)',
    'Fruit Platter Station',
    'Chocolate Fountain',
    'Imported Cheese Board',
  ],
}

// ──────────────────────────────────────────────────────
// NON-VEGETARIAN BANQUET PACKAGES
// ──────────────────────────────────────────────────────

export const NON_VEG_PREMIUM: BanquetPackage = {
  id: 'non-veg-premium',
  name: 'Premium Non-Veg Banquet',
  mealType: 'non-veg',
  pricePerHead: 2650,
  tagline: '₹2,650 per head · A rich non-vegetarian banquet experience',
  categories: [
    {
      id: 'welcome-drinks',
      label: 'Welcome Drinks',
      emoji: '🥤',
      limit: 2,
      items: [
        { name: 'Mango Lassi' },
        { name: 'Rose Sherbat' },
        { name: 'Lemon Mint Cooler' },
        { name: 'Jaljeera' },
        { name: 'Aam Panna' },
        { name: 'Masala Chach (Buttermilk)' },
        { name: 'Coconut Water' },
      ],
    },
    {
      id: 'starters-nonveg-indian',
      label: 'Starters — Non-Veg Indian',
      emoji: '🍗',
      limit: 4,
      items: [
        { name: 'Chicken Tikka' },
        { name: 'Seekh Kebab' },
        { name: 'Murgh Malai Tikka' },
        { name: 'Achari Chicken Tikka' },
        { name: 'Tandoori Chicken (half)' },
        { name: 'Mutton Sheekh Kebab' },
        { name: 'Galouti Kebab' },
        { name: 'Raan Tikka' },
      ],
    },
    {
      id: 'starters-nonveg-oriental',
      label: 'Starters — Non-Veg Oriental & Western',
      emoji: '🥡',
      limit: 2,
      items: [
        { name: 'Chicken Manchurian (Dry)' },
        { name: 'Chilli Chicken (Dry)' },
        { name: 'Fish Amritsari' },
        { name: 'Tandoori Prawns' },
        { name: 'Honey Chilli Chicken' },
        { name: 'Chicken Lollipop' },
      ],
    },
    {
      id: 'soup',
      label: 'Soup',
      emoji: '🍲',
      limit: 2,
      items: [
        { name: 'Chicken Shorba' },
        { name: 'Tomato Shorba' },
        { name: 'Mulligatawny Soup' },
        { name: 'Sweet Corn Chicken Soup' },
        { name: 'Hot & Sour Chicken Soup' },
        { name: 'Mutton Nihari Soup' },
      ],
    },
    {
      id: 'salads',
      label: 'Salads',
      emoji: '🥙',
      limit: 4,
      items: [
        { name: 'Green Salad' },
        { name: 'Russian Salad' },
        { name: 'Chicken Caesar Salad' },
        { name: 'Coleslaw' },
        { name: 'Fruit Salad' },
        { name: 'Pasta Salad' },
        { name: 'Corn Salad' },
      ],
    },
    {
      id: 'raita-curd',
      label: 'Raita / Curd',
      emoji: '🫙',
      limit: 1,
      items: [
        { name: 'Boondi Raita' },
        { name: 'Mixed Raita' },
        { name: 'Cucumber Raita' },
        { name: 'Plain Curd' },
      ],
    },
    {
      id: 'nonveg-main',
      label: 'Non-Veg Main Course',
      emoji: '🍖',
      limit: 3,
      items: [
        { name: 'Butter Chicken' },
        { name: 'Murgh Saagwala' },
        { name: 'Kadai Chicken' },
        { name: 'Chicken Lababdar' },
        { name: 'Mutton Rogan Josh' },
        { name: 'Mutton Korma' },
        { name: 'Keema Matar' },
        { name: 'Fish Curry' },
        { name: 'Prawn Masala' },
      ],
    },
    {
      id: 'veg-main',
      label: 'Veg Main Course (accompaniment)',
      emoji: '🍛',
      limit: 2,
      items: [
        { name: 'Paneer Butter Masala' },
        { name: 'Dal Makhani' },
        { name: 'Mix Vegetable' },
        { name: 'Aloo Gobi' },
        { name: 'Navratan Korma' },
      ],
    },
    {
      id: 'dal',
      label: 'Dal',
      emoji: '🫕',
      limit: 1,
      items: [
        { name: 'Dal Makhani' },
        { name: 'Dal Tadka' },
        { name: 'Dal Fry' },
        { name: 'Chana Masala' },
      ],
    },
    {
      id: 'rice-noodles',
      label: 'Rice / Noodles',
      emoji: '🍚',
      limit: 2,
      items: [
        { name: 'Steamed Rice' },
        { name: 'Jeera Rice' },
        { name: 'Chicken Biryani' },
        { name: 'Mutton Biryani' },
        { name: 'Egg Fried Rice' },
        { name: 'Chicken Hakka Noodles' },
      ],
    },
    {
      id: 'breads',
      label: 'Breads (Assorted)',
      emoji: '🫓',
      items: [
        { name: 'Butter Naan' },
        { name: 'Tandoori Roti' },
        { name: 'Laccha Paratha' },
        { name: 'Missi Roti' },
        { name: 'Kulcha' },
      ],
    },
    {
      id: 'desserts',
      label: 'Desserts',
      emoji: '🍮',
      limit: 4,
      items: [
        { name: 'Gulab Jamun' },
        { name: 'Rasgulla' },
        { name: 'Kheer' },
        { name: 'Gajar Halwa' },
        { name: 'Phirni' },
        { name: 'Ras Malai' },
        { name: 'Kulfi Falooda' },
        { name: 'Jalebi with Rabri' },
        { name: 'Ice Cream (2 flavours)' },
      ],
    },
  ],
  liveStations: [
    {
      id: 'tawa',
      label: 'Tawa Tak-A-Tak Station',
      subItems: [
        'Tawa Chicken',
        'Tawa Mutton',
        'Tawa Paneer',
        'Tawa Aloo',
      ],
    },
    {
      id: 'chaat',
      label: 'Chaat Corner',
      subItems: [
        'Pani Puri',
        'Sev Puri',
        'Bhel Puri',
        'Dahi Bhalla',
      ],
    },
    {
      id: 'ice-cream',
      label: 'Ice Cream Counter',
      subItems: [
        'Vanilla',
        'Chocolate',
        'Strawberry',
        'Butterscotch',
        'Mango',
      ],
    },
  ],
  addOns: [
    'High Tea (per head surcharge)',
    'Mocktail Bar Setup',
    'Paan Counter',
    'Extra Live Station',
    'Extended Service (per hour)',
  ],
}

export const NON_VEG_EXECUTIVE: BanquetPackage = {
  id: 'non-veg-executive',
  name: 'Executive Non-Veg Banquet',
  mealType: 'non-veg',
  pricePerHead: 3150,
  tagline: '₹3,150 per head · A premium non-vegetarian feast with extra variety',
  categories: [
    {
      id: 'welcome-drinks',
      label: 'Welcome Drinks',
      emoji: '🥤',
      limit: 3,
      items: [
        { name: 'Mango Lassi' },
        { name: 'Rose Sherbat' },
        { name: 'Lemon Mint Cooler' },
        { name: 'Jaljeera' },
        { name: 'Aam Panna' },
        { name: 'Masala Chach (Buttermilk)' },
        { name: 'Coconut Water' },
        { name: 'Fresh Lime Soda' },
      ],
    },
    {
      id: 'starters-nonveg-indian',
      label: 'Starters — Non-Veg Indian',
      emoji: '🍗',
      limit: 5,
      items: [
        { name: 'Chicken Tikka' },
        { name: 'Seekh Kebab' },
        { name: 'Murgh Malai Tikka' },
        { name: 'Achari Chicken Tikka' },
        { name: 'Tandoori Chicken (half)' },
        { name: 'Mutton Sheekh Kebab' },
        { name: 'Galouti Kebab' },
        { name: 'Raan Tikka' },
        { name: 'Fish Tikka' },
        { name: 'Jhinga (Prawn) Tikka' },
      ],
    },
    {
      id: 'starters-nonveg-oriental',
      label: 'Starters — Non-Veg Oriental & Western',
      emoji: '🥡',
      limit: 3,
      items: [
        { name: 'Chicken Manchurian (Dry)' },
        { name: 'Chilli Chicken (Dry)' },
        { name: 'Fish Amritsari' },
        { name: 'Tandoori Prawns' },
        { name: 'Honey Chilli Chicken' },
        { name: 'Chicken Lollipop' },
        { name: 'Mutton Seekh (Oriental)' },
      ],
    },
    {
      id: 'soup',
      label: 'Soup',
      emoji: '🍲',
      limit: 2,
      items: [
        { name: 'Chicken Shorba' },
        { name: 'Tomato Shorba' },
        { name: 'Mulligatawny Soup' },
        { name: 'Sweet Corn Chicken Soup' },
        { name: 'Hot & Sour Chicken Soup' },
        { name: 'Mutton Nihari Soup' },
        { name: 'Tom Kha Gai (Thai)' },
      ],
    },
    {
      id: 'salads',
      label: 'Salads',
      emoji: '🥙',
      limit: 5,
      items: [
        { name: 'Green Salad' },
        { name: 'Russian Salad' },
        { name: 'Chicken Caesar Salad' },
        { name: 'Coleslaw' },
        { name: 'Fruit Salad' },
        { name: 'Pasta Salad' },
        { name: 'Corn Salad' },
        { name: 'Grilled Chicken Salad' },
        { name: 'Thai Salad' },
      ],
    },
    {
      id: 'raita-curd',
      label: 'Raita / Curd',
      emoji: '🫙',
      limit: 1,
      items: [
        { name: 'Boondi Raita' },
        { name: 'Mixed Raita' },
        { name: 'Cucumber Raita' },
        { name: 'Plain Curd' },
      ],
    },
    {
      id: 'nonveg-main',
      label: 'Non-Veg Main Course',
      emoji: '🍖',
      limit: 4,
      items: [
        { name: 'Butter Chicken' },
        { name: 'Murgh Saagwala' },
        { name: 'Kadai Chicken' },
        { name: 'Chicken Lababdar' },
        { name: 'Mutton Rogan Josh' },
        { name: 'Mutton Korma' },
        { name: 'Keema Matar' },
        { name: 'Fish Curry' },
        { name: 'Prawn Masala' },
        { name: 'Chicken Chettinad' },
      ],
    },
    {
      id: 'veg-main',
      label: 'Veg Main Course (accompaniment)',
      emoji: '🍛',
      limit: 2,
      items: [
        { name: 'Paneer Butter Masala' },
        { name: 'Dal Makhani' },
        { name: 'Mix Vegetable' },
        { name: 'Aloo Gobi' },
        { name: 'Navratan Korma' },
      ],
    },
    {
      id: 'dal',
      label: 'Dal',
      emoji: '🫕',
      limit: 1,
      items: [
        { name: 'Dal Makhani' },
        { name: 'Dal Tadka' },
        { name: 'Dal Fry' },
        { name: 'Chana Masala' },
        { name: 'Rajma Masala' },
      ],
    },
    {
      id: 'rice-noodles',
      label: 'Rice / Noodles',
      emoji: '🍚',
      limit: 2,
      items: [
        { name: 'Steamed Rice' },
        { name: 'Jeera Rice' },
        { name: 'Chicken Biryani' },
        { name: 'Mutton Biryani' },
        { name: 'Egg Fried Rice' },
        { name: 'Chicken Hakka Noodles' },
        { name: 'Prawn Fried Rice' },
      ],
    },
    {
      id: 'breads',
      label: 'Breads (Assorted)',
      emoji: '🫓',
      items: [
        { name: 'Butter Naan' },
        { name: 'Tandoori Roti' },
        { name: 'Laccha Paratha' },
        { name: 'Missi Roti' },
        { name: 'Garlic Naan' },
      ],
    },
    {
      id: 'desserts',
      label: 'Desserts',
      emoji: '🍮',
      limit: 5,
      items: [
        { name: 'Gulab Jamun' },
        { name: 'Rasgulla' },
        { name: 'Kheer' },
        { name: 'Gajar Halwa' },
        { name: 'Phirni' },
        { name: 'Ras Malai' },
        { name: 'Kulfi Falooda' },
        { name: 'Jalebi with Rabri' },
        { name: 'Ice Cream (3 flavours)' },
        { name: 'Shahi Tukda' },
      ],
    },
  ],
  liveStations: [
    {
      id: 'tawa',
      label: 'Tawa Tak-A-Tak Station',
      subItems: [
        'Tawa Chicken',
        'Tawa Mutton',
        'Tawa Paneer',
        'Tawa Aloo',
      ],
    },
    {
      id: 'chaat',
      label: 'Chaat Corner',
      subItems: [
        'Pani Puri',
        'Sev Puri',
        'Bhel Puri',
        'Dahi Bhalla',
      ],
    },
    {
      id: 'pasta',
      label: 'Pasta & Pizza Station',
      subItems: [
        'Penne Arrabbiata',
        'Mac & Cheese',
        'Chicken Pizza',
      ],
    },
    {
      id: 'ice-cream',
      label: 'Ice Cream Counter',
      subItems: [
        'Vanilla',
        'Chocolate',
        'Strawberry',
        'Butterscotch',
        'Mango',
        'Pista',
      ],
    },
  ],
  addOns: [
    'High Tea (per head surcharge)',
    'Mocktail Bar Setup',
    'Paan Counter',
    'Extra Live Station',
    'Extended Service (per hour)',
    'Fruit Platter Station',
  ],
}

export const NON_VEG_PLATINUM: BanquetPackage = {
  id: 'non-veg-platinum',
  name: 'Platinum Non-Veg Banquet',
  mealType: 'non-veg',
  pricePerHead: 3650,
  tagline: '₹3,650 per head · The ultimate luxury non-vegetarian banquet',
  categories: [
    {
      id: 'welcome-drinks',
      label: 'Welcome Drinks',
      emoji: '🥤',
      limit: 4,
      items: [
        { name: 'Mango Lassi' },
        { name: 'Rose Sherbat' },
        { name: 'Lemon Mint Cooler' },
        { name: 'Jaljeera' },
        { name: 'Aam Panna' },
        { name: 'Masala Chach (Buttermilk)' },
        { name: 'Coconut Water' },
        { name: 'Fresh Lime Soda' },
        { name: 'Gondhoraj Nimbu Sherbat' },
      ],
    },
    {
      id: 'starters-nonveg-indian',
      label: 'Starters — Non-Veg Indian',
      emoji: '🍗',
      limit: 6,
      items: [
        { name: 'Chicken Tikka' },
        { name: 'Seekh Kebab' },
        { name: 'Murgh Malai Tikka' },
        { name: 'Achari Chicken Tikka' },
        { name: 'Tandoori Chicken (half)' },
        { name: 'Mutton Sheekh Kebab' },
        { name: 'Galouti Kebab' },
        { name: 'Raan Tikka' },
        { name: 'Fish Tikka' },
        { name: 'Jhinga (Prawn) Tikka' },
        { name: 'Peshwari Murgh' },
        { name: 'Burrah Kebab' },
      ],
    },
    {
      id: 'starters-nonveg-oriental',
      label: 'Starters — Non-Veg Oriental & Western',
      emoji: '🥡',
      limit: 4,
      items: [
        { name: 'Chicken Manchurian (Dry)' },
        { name: 'Chilli Chicken (Dry)' },
        { name: 'Fish Amritsari' },
        { name: 'Tandoori Prawns' },
        { name: 'Honey Chilli Chicken' },
        { name: 'Chicken Lollipop' },
        { name: 'Mutton Seekh (Oriental)' },
        { name: 'Prawn Tempura' },
      ],
    },
    {
      id: 'soup',
      label: 'Soup',
      emoji: '🍲',
      limit: 2,
      items: [
        { name: 'Chicken Shorba' },
        { name: 'Tomato Shorba' },
        { name: 'Mulligatawny Soup' },
        { name: 'Sweet Corn Chicken Soup' },
        { name: 'Hot & Sour Chicken Soup' },
        { name: 'Mutton Nihari Soup' },
        { name: 'Tom Kha Gai (Thai)' },
        { name: 'Wonton Soup' },
      ],
    },
    {
      id: 'salads',
      label: 'Salads',
      emoji: '🥙',
      limit: 6,
      items: [
        { name: 'Green Salad' },
        { name: 'Russian Salad' },
        { name: 'Chicken Caesar Salad' },
        { name: 'Coleslaw' },
        { name: 'Fruit Salad' },
        { name: 'Pasta Salad' },
        { name: 'Corn Salad' },
        { name: 'Grilled Chicken Salad' },
        { name: 'Thai Salad' },
        { name: 'Smoked Salmon Salad' },
      ],
    },
    {
      id: 'raita-curd',
      label: 'Raita / Curd',
      emoji: '🫙',
      limit: 1,
      items: [
        { name: 'Boondi Raita' },
        { name: 'Mixed Raita' },
        { name: 'Cucumber Raita' },
        { name: 'Plain Curd' },
      ],
    },
    {
      id: 'nonveg-main',
      label: 'Non-Veg Main Course',
      emoji: '🍖',
      limit: 5,
      items: [
        { name: 'Butter Chicken' },
        { name: 'Murgh Saagwala' },
        { name: 'Kadai Chicken' },
        { name: 'Chicken Lababdar' },
        { name: 'Mutton Rogan Josh' },
        { name: 'Mutton Korma' },
        { name: 'Keema Matar' },
        { name: 'Fish Curry' },
        { name: 'Prawn Masala' },
        { name: 'Chicken Chettinad' },
        { name: 'Nawabi Murgh' },
        { name: 'Nihari Gosht' },
      ],
    },
    {
      id: 'veg-main',
      label: 'Veg Main Course (accompaniment)',
      emoji: '🍛',
      limit: 2,
      items: [
        { name: 'Paneer Butter Masala' },
        { name: 'Dal Makhani' },
        { name: 'Mix Vegetable' },
        { name: 'Aloo Gobi' },
        { name: 'Navratan Korma' },
      ],
    },
    {
      id: 'dal',
      label: 'Dal',
      emoji: '🫕',
      limit: 1,
      items: [
        { name: 'Dal Makhani' },
        { name: 'Dal Tadka' },
        { name: 'Dal Fry' },
        { name: 'Chana Masala' },
        { name: 'Rajma Masala' },
        { name: 'Amti Dal' },
      ],
    },
    {
      id: 'rice-noodles',
      label: 'Rice / Noodles',
      emoji: '🍚',
      limit: 2,
      items: [
        { name: 'Steamed Rice' },
        { name: 'Jeera Rice' },
        { name: 'Chicken Biryani' },
        { name: 'Mutton Biryani' },
        { name: 'Egg Fried Rice' },
        { name: 'Chicken Hakka Noodles' },
        { name: 'Prawn Fried Rice' },
        { name: 'Zaffrani Biryani' },
      ],
    },
    {
      id: 'breads',
      label: 'Breads (Assorted)',
      emoji: '🫓',
      items: [
        { name: 'Butter Naan' },
        { name: 'Tandoori Roti' },
        { name: 'Laccha Paratha' },
        { name: 'Missi Roti' },
        { name: 'Garlic Naan' },
        { name: 'Stuffed Naan' },
      ],
    },
    {
      id: 'desserts',
      label: 'Desserts',
      emoji: '🍮',
      limit: 6,
      items: [
        { name: 'Gulab Jamun' },
        { name: 'Rasgulla' },
        { name: 'Kheer' },
        { name: 'Gajar Halwa' },
        { name: 'Phirni' },
        { name: 'Ras Malai' },
        { name: 'Kulfi Falooda' },
        { name: 'Jalebi with Rabri' },
        { name: 'Ice Cream (3 flavours)' },
        { name: 'Shahi Tukda' },
        { name: 'Malpua with Rabri' },
        { name: 'Badam Halwa' },
      ],
    },
  ],
  liveStations: [
    {
      id: 'tawa',
      label: 'Tawa Tak-A-Tak Station',
      subItems: [
        'Tawa Chicken',
        'Tawa Mutton',
        'Tawa Paneer',
        'Tawa Aloo',
        'Tawa Mixed Vegetables',
      ],
    },
    {
      id: 'chaat',
      label: 'Chaat Corner',
      subItems: [
        'Pani Puri',
        'Sev Puri',
        'Bhel Puri',
        'Dahi Bhalla',
        'Raj Kachori',
      ],
    },
    {
      id: 'pasta',
      label: 'Pasta & Pizza Station',
      subItems: [
        'Penne Arrabbiata',
        'Mac & Cheese',
        'Spaghetti Aglio e Olio',
        'Chicken Pizza',
        'Pepperoni Pizza',
      ],
    },
    {
      id: 'indian-sweets',
      label: 'Live Indian Sweets Counter',
      subItems: [
        'Jalebi (freshly fried)',
        'Gulab Jamun (warm)',
        'Malpua',
      ],
    },
    {
      id: 'ice-cream',
      label: 'Ice Cream & Dessert Counter',
      subItems: [
        'Vanilla',
        'Chocolate',
        'Strawberry',
        'Butterscotch',
        'Mango',
        'Pista',
        'Kulfi (Malai)',
      ],
    },
  ],
  addOns: [
    'High Tea (per head surcharge)',
    'Mocktail Bar Setup',
    'Paan Counter',
    'Extra Live Station',
    'Extended Service (per hour)',
    'Fruit Platter Station',
    'Chocolate Fountain',
    'Imported Cheese Board',
  ],
}

// ──────────────────────────────────────────────────────
// Helpers
// ──────────────────────────────────────────────────────

export const ALL_BANQUET_PACKAGES: BanquetPackage[] = [
  VEG_PREMIUM,
  VEG_EXECUTIVE,
  VEG_PLATINUM,
  NON_VEG_PREMIUM,
  NON_VEG_EXECUTIVE,
  NON_VEG_PLATINUM,
]

/** Return the banquet packages matching a given food preference. */
export function getPackagesForMealType(mealType: 'veg' | 'non-veg'): BanquetPackage[] {
  return ALL_BANQUET_PACKAGES.filter((p) => p.mealType === mealType)
}

/** Find a package by ID. */
export function findPackageById(id: string): BanquetPackage | undefined {
  return ALL_BANQUET_PACKAGES.find((p) => p.id === id)
}
