// -------------------------------------------------------
// Mannat Events — Banquet Menu Library
// Source: Supplied banquet/package PDF documentation
// DO NOT invent items or limits not in the source data.
// -------------------------------------------------------

import type { BanquetPackage } from './types'

// ──────────────────────────────────────────────────────
// DISH DEFINITIONS FROM BANQUET PDF
// ──────────────────────────────────────────────────────

const VEG_STARTERS_INDIAN_REGULAR = [
  { name: 'Aloo Pudina Tikki' },
  { name: 'Assorted Veg Pakoda' },
  { name: 'Cocktail Matar Samosa' },
  { name: 'Pyaaz Ki Kachori' },
  { name: 'Fried Idli' },
  { name: 'Dhokla' },
  { name: 'Moong Dal Pakodi' },
  { name: 'Tandoori Charra Aloo' },
  { name: 'Masala Fries' },
  { name: 'Tandoori Gobhi' },
  { name: 'Soya Tikka' },
]

const VEG_STARTERS_INDIAN_PREMIUM = [
  { name: 'Paneer Tikka' },
  { name: 'Masala Paneer Fingers' },
  { name: 'Paneer Pakoda' },
  { name: 'Chutney Paneer Tikka' },
  { name: 'Papad Paneer Tikka' },
  { name: 'Dahi Ke Kebab' },
  { name: 'Hare Matar Ki Tikki' },
  { name: 'Tandoori Khumb' },
  { name: 'Jimikand Aur Anjeer Ke Kebab' },
  { name: 'Palak Aur Chenna Kebab' },
  { name: 'Beetroot Kebab' },
  { name: 'Paneer 65' },
]

const VEG_STARTERS_INDIAN_SUPER_PREMIUM = [
  { name: 'Pesto Paneer Tikka' },
  { name: 'Tandoori Broccoli with Feta Cheese' },
  { name: 'Peanut Butter Paneer Tikka' },
  { name: 'Tandoori Mushroom with Parmesan Cheese' },
  { name: 'Pulled Kathal over Ulta Tawa Parantha' },
  { name: 'Soya Kurchan Roll' },
  { name: 'Paneer Bhurjee Sliders' },
  { name: 'Palak Patta Chaat' },
  { name: 'Dahi Batat Puri' },
  { name: 'Dumpukht Hara Kebabon Ulta Tawa Parantha' },
]

const VEG_STARTERS_ORIENTAL_REGULAR = [
  { name: 'Vegetarian Salt and Pepper' },
  { name: 'Veg Manchurian Dry' },
  { name: 'Honey Chilly Potatoes' },
  { name: 'Veg Spring Roll' },
  { name: 'Chilly and Pepper Tossed Cauliflower' },
  { name: 'Hummus with Pita' },
  { name: 'Falafel Kebab with Mint Hummus' },
  { name: 'Assorted Sandwiches' },
  { name: 'Veg Croquette' },
  { name: 'Mushroom Vol Au Vent' },
  { name: 'French Fries' },
  { name: 'Veg Sandwich' },
  { name: 'Veg Puff' },
  { name: 'Veg Cutlet' },
]

const VEG_STARTERS_ORIENTAL_PREMIUM = [
  { name: 'Golden Fried Baby Corn' },
  { name: 'Chilly Paneer' },
  { name: 'Chilly Mushroom' },
  { name: 'Veg Momos' },
  { name: 'Corn and Cheese Spring Roll' },
  { name: 'Cheese and Sticks' },
  { name: 'Spinach and Corn Cake' },
  { name: 'Home Fries with Peri Peri Spice' },
  { name: 'Grilled Sandwich' },
]

const VEG_STARTERS_ORIENTAL_SUPER_PREMIUM = [
  { name: 'Veg Yakitori' },
  { name: 'Chilly Tofu' },
  { name: 'Veg Satay Peanut Sauce' },
  { name: 'Mushroom Arancini' },
  { name: 'Sticky Rice Arancini' },
  { name: 'Mushroom Crostini' },
  { name: 'Beetroot and Rocket Crostini' },
  { name: 'Grilled Cottage Cheese with Oregano' },
  { name: 'Mushroom Duplex' },
]

const NON_VEG_STARTERS_INDIAN_REGULAR = [
  { name: 'Amritsari Fish Fingers' },
  { name: 'Chicken Tikka Peshawar' },
  { name: 'Seekh Kebab' },
  { name: 'Reshmi Kebab' },
  { name: 'Shammi Kebab' },
  { name: 'Chicken Afghani Tikka' },
]

const NON_VEG_STARTERS_INDIAN_PREMIUM = [
  { name: 'Chicken Malai Tikka' },
  { name: 'Chicken Smoked Barbeque Tikka' },
  { name: 'Chicken Kali Mirch Tikka' },
  { name: 'Sumac Zartar Chicken Tikka with Pomegranates' },
  { name: 'Chicken 65' },
  { name: 'Gilafi Seekh' },
  { name: 'Machli Methi Tikka' },
  { name: 'Fish Annari Tikka' },
  { name: 'Grilled Chicken and Cheese Sandwich' },
]

const NON_VEG_STARTERS_INDIAN_SUPER_PREMIUM = [
  { name: 'Fish Tikka (River Sole)' },
  { name: 'Fish Tawa Fry (River Sole)' },
  { name: 'Chicken Zaituni Malai with Olives' },
  { name: 'Keema on Small Parantha' },
  { name: 'Pulled Tandoori Chicken Roll with Makhni Dip' },
  { name: 'Mutton Tikka' },
  { name: 'Patthar Ke Kebab' },
  { name: 'Galawat Kebab' },
]

const NON_VEG_STARTERS_ORIENTAL_REGULAR = [
  { name: 'Drums of Heaven' },
  { name: 'Chili Chicken Dry' },
  { name: 'Chili Fish' },
  { name: 'Chicken Salt and Pepper' },
  { name: 'Fish Finger with Tarter' },
  { name: 'Country Fried Chicken with Barbeque Dip' },
  { name: 'Chicken Puff' },
  { name: 'Chicken Sandwich' },
]

const NON_VEG_STARTERS_ORIENTAL_PREMIUM = [
  { name: 'Crispy Fried Chicken Wonton' },
  { name: 'Chicken and Cheese Spring Roll' },
  { name: 'Chicken Satay' },
  { name: 'Chicken Yakitori' },
  { name: 'Chicken Momos' },
  { name: 'Lamb Satay with Green Curry Sauce' },
  { name: 'Tuscan Meat Balls' },
  { name: 'Beer Batter Fish' },
  { name: 'Fish Orly' },
  { name: 'Olive and Chicken Sticks' },
  { name: 'Barbeque Chicken Sausages' },
  { name: 'Chicken Vol Au Vent' },
  { name: 'Smoked Chicken Breast Crostini' },
]

const PRAWN_STARTERS = [
  { name: 'Golden Fried Prawns' },
  { name: 'Prawns Tandoori' },
  { name: 'Shrimp Cocktail' },
  { name: 'Bloody Mary Prawns' },
  { name: 'Kadhai Jhinga' },
]

const PDF_ADDONS = [
  'Pasta Live / Trolley (₹250/head)',
  'Chaat Counter (₹450/head)',
  'Jalebi with Rabri Live (₹199/head)',
  'High Tea (₹350/head)',
  'Mocktail Bar Setup (₹400/head)',
  'Paan Counter (₹150/head)',
  'Extra Live Station (₹300/head)',
  'Fruit Platter Station (₹250/head)',
  'Chocolate Fountain (₹200/head)',
  'Imported Cheese Board (₹500/head)',
]

// ──────────────────────────────────────────────────────
// VEGETARIAN BANQUET PACKAGES
// ──────────────────────────────────────────────────────

export const VEG_PREMIUM: BanquetPackage = {
  id: 'veg-premium',
  name: 'Premium Veg Banquet',
  mealType: 'veg',
  pricePerHead: 2000,
  tagline: '₹2,000 per head · A rich vegetarian banquet experience',
  categories: [
    {
      id: 'welcome-drinks',
      label: 'Welcome Drinks',
      emoji: '🥤',
      limit: 2,
      items: [
        { name: 'Mango Lassi' },
        { name: 'Rose Sherbat' },
        { name: 'Lemon Mint Cooler' },
        { name: 'Jaljeera' },
        { name: 'Aam Panna' },
        { name: 'Thandai' },
        { name: 'Masala Chach (Buttermilk)' },
        { name: 'Coconut Water' },
      ],
    },
    {
      id: 'starters-veg-indian',
      label: 'Starters — Veg Indian',
      emoji: '🥗',
      limit: 4,
      items: [...VEG_STARTERS_INDIAN_REGULAR, ...VEG_STARTERS_INDIAN_PREMIUM],
    },
    {
      id: 'starters-veg-oriental',
      label: 'Starters — Veg Oriental & Western',
      emoji: '🥡',
      limit: 2,
      items: [...VEG_STARTERS_ORIENTAL_REGULAR, ...VEG_STARTERS_ORIENTAL_PREMIUM],
    },
    {
      id: 'soup',
      label: 'Soup',
      emoji: '🍲',
      limit: 2,
      items: [
        { name: 'Tomato Shorba' },
        { name: 'Sweet Corn Vegetable Soup' },
        { name: 'Dal Shorba' },
        { name: 'Mulligatawny Soup (Veg)' },
        { name: 'Mushroom Cream Soup' },
        { name: 'Hot & Sour Vegetable Soup' },
      ],
    },
    {
      id: 'salads',
      label: 'Salads',
      emoji: '🥙',
      limit: 4,
      items: [
        { name: 'Green Salad' },
        { name: 'Russian Salad' },
        { name: 'Sprouts Salad' },
        { name: 'Corn Salad' },
        { name: 'Pasta Salad' },
        { name: 'Coleslaw' },
        { name: 'Fruit Salad' },
        { name: 'Papdi Chaat' },
      ],
    },
    {
      id: 'raita-curd',
      label: 'Raita / Curd',
      emoji: '🫙',
      limit: 1,
      items: [
        { name: 'Boondi Raita' },
        { name: 'Mixed Raita' },
        { name: 'Cucumber Raita' },
        { name: 'Plain Curd' },
        { name: 'Pineapple Raita' },
      ],
    },
    {
      id: 'paneer-main',
      label: 'Paneer Main Course',
      emoji: '🧀',
      limit: 2,
      items: [
        { name: 'Paneer Butter Masala' },
        { name: 'Shahi Paneer' },
        { name: 'Kadai Paneer' },
        { name: 'Palak Paneer' },
        { name: 'Paneer Lababdar' },
        { name: 'Paneer Makhani' },
      ],
    },
    {
      id: 'veg-main',
      label: 'Veg Main Course',
      emoji: '🍛',
      limit: 3,
      items: [
        { name: 'Aloo Gobi' },
        { name: 'Veg Kolhapuri' },
        { name: 'Matar Mushroom' },
        { name: 'Bhindi Masala' },
        { name: 'Lauki Kofta' },
        { name: 'Mix Vegetable' },
        { name: 'Dum Aloo' },
        { name: 'Navratan Korma' },
      ],
    },
    {
      id: 'dal',
      label: 'Dal',
      emoji: '🫕',
      limit: 1,
      items: [
        { name: 'Dal Makhani' },
        { name: 'Dal Tadka' },
        { name: 'Dal Fry' },
        { name: 'Panchmel Dal' },
        { name: 'Chana Masala' },
      ],
    },
    {
      id: 'rice-noodles',
      label: 'Rice / Noodles',
      emoji: '🍚',
      limit: 2,
      items: [
        { name: 'Steamed Rice' },
        { name: 'Jeera Rice' },
        { name: 'Veg Pulao' },
        { name: 'Veg Biryani' },
        { name: 'Schezwan Fried Rice' },
        { name: 'Veg Hakka Noodles' },
      ],
    },
    {
      id: 'breads',
      label: 'Breads (Assorted)',
      emoji: '🫓',
      items: [
        { name: 'Butter Naan' },
        { name: 'Tandoori Roti' },
        { name: 'Laccha Paratha' },
        { name: 'Missi Roti' },
        { name: 'Kulcha' },
      ],
    },
    {
      id: 'desserts',
      label: 'Desserts',
      emoji: '🍮',
      limit: 4,
      items: [
        { name: 'Gulab Jamun' },
        { name: 'Rasgulla' },
        { name: 'Kheer' },
        { name: 'Gajar Halwa' },
        { name: 'Moong Dal Halwa' },
        { name: 'Phirni' },
        { name: 'Jalebi with Rabri' },
        { name: 'Ras Malai' },
        { name: 'Kulfi Falooda' },
      ],
    },
  ],
  liveStations: [
    {
      id: 'tawa',
      label: 'Tawa Tak-A-Tak Station',
      subItems: ['Tawa Paneer', 'Tawa Aloo', 'Tawa Mushroom', 'Tawa Gobhi'],
    },
    {
      id: 'chaat',
      label: 'Chaat Corner',
      subItems: ['Pani Puri', 'Sev Puri', 'Bhel Puri', 'Dahi Bhalla'],
    },
    {
      id: 'ice-cream',
      label: 'Ice Cream Counter',
      subItems: ['Vanilla', 'Chocolate', 'Strawberry', 'Butterscotch', 'Mango'],
    },
  ],
  addOns: PDF_ADDONS,
}

export const VEG_EXECUTIVE: BanquetPackage = {
  id: 'veg-executive',
  name: 'Executive Veg Banquet',
  mealType: 'veg',
  pricePerHead: 2500,
  tagline: '₹2,500 per head · A premium vegetarian feast with extra variety',
  categories: [
    {
      id: 'welcome-drinks',
      label: 'Welcome Drinks',
      emoji: '🥤',
      limit: 3,
      items: [
        { name: 'Mango Lassi' },
        { name: 'Rose Sherbat' },
        { name: 'Lemon Mint Cooler' },
        { name: 'Jaljeera' },
        { name: 'Aam Panna' },
        { name: 'Thandai' },
        { name: 'Masala Chach (Buttermilk)' },
        { name: 'Coconut Water' },
        { name: 'Fresh Lime Soda' },
      ],
    },
    {
      id: 'starters-veg-indian',
      label: 'Starters — Veg Indian',
      emoji: '🥗',
      limit: 5,
      items: [...VEG_STARTERS_INDIAN_PREMIUM, ...VEG_STARTERS_INDIAN_SUPER_PREMIUM],
    },
    {
      id: 'starters-veg-oriental',
      label: 'Starters — Veg Oriental & Western',
      emoji: '🥡',
      limit: 3,
      items: [...VEG_STARTERS_ORIENTAL_PREMIUM, ...VEG_STARTERS_ORIENTAL_SUPER_PREMIUM],
    },
    {
      id: 'soup',
      label: 'Soup',
      emoji: '🍲',
      limit: 2,
      items: [
        { name: 'Tomato Shorba' },
        { name: 'Sweet Corn Vegetable Soup' },
        { name: 'Dal Shorba' },
        { name: 'Mulligatawny Soup (Veg)' },
        { name: 'Mushroom Cream Soup' },
        { name: 'Hot & Sour Vegetable Soup' },
        { name: 'Lemon Coriander Soup' },
      ],
    },
    {
      id: 'salads',
      label: 'Salads',
      emoji: '🥙',
      limit: 5,
      items: [
        { name: 'Green Salad' },
        { name: 'Russian Salad' },
        { name: 'Sprouts Salad' },
        { name: 'Corn Salad' },
        { name: 'Pasta Salad' },
        { name: 'Coleslaw' },
        { name: 'Fruit Salad' },
        { name: 'Papdi Chaat' },
        { name: 'Greek Salad' },
        { name: 'Thai Salad' },
      ],
    },
    {
      id: 'raita-curd',
      label: 'Raita / Curd',
      emoji: '🫙',
      limit: 1,
      items: [
        { name: 'Boondi Raita' },
        { name: 'Mixed Raita' },
        { name: 'Cucumber Raita' },
        { name: 'Plain Curd' },
        { name: 'Pineapple Raita' },
      ],
    },
    {
      id: 'paneer-main',
      label: 'Paneer Main Course',
      emoji: '🧀',
      limit: 2,
      items: [
        { name: 'Paneer Butter Masala' },
        { name: 'Shahi Paneer' },
        { name: 'Kadai Paneer' },
        { name: 'Palak Paneer' },
        { name: 'Paneer Lababdar' },
        { name: 'Paneer Makhani' },
        { name: 'Paneer Pasanda' },
      ],
    },
    {
      id: 'veg-main',
      label: 'Veg Main Course',
      emoji: '🍛',
      limit: 4,
      items: [
        { name: 'Aloo Gobi' },
        { name: 'Veg Kolhapuri' },
        { name: 'Matar Mushroom' },
        { name: 'Bhindi Masala' },
        { name: 'Lauki Kofta' },
        { name: 'Mix Vegetable' },
        { name: 'Dum Aloo' },
        { name: 'Navratan Korma' },
        { name: 'Tindora Masala' },
        { name: 'Veg Jaipuri' },
      ],
    },
    {
      id: 'dal',
      label: 'Dal',
      emoji: '🫕',
      limit: 1,
      items: [
        { name: 'Dal Makhani' },
        { name: 'Dal Tadka' },
        { name: 'Dal Fry' },
        { name: 'Panchmel Dal' },
        { name: 'Chana Masala' },
        { name: 'Rajma Masala' },
      ],
    },
    {
      id: 'rice-noodles',
      label: 'Rice / Noodles',
      emoji: '🍚',
      limit: 2,
      items: [
        { name: 'Steamed Rice' },
        { name: 'Jeera Rice' },
        { name: 'Veg Pulao' },
        { name: 'Veg Biryani' },
        { name: 'Schezwan Fried Rice' },
        { name: 'Veg Hakka Noodles' },
        { name: 'Kashmiri Pulao' },
      ],
    },
    {
      id: 'breads',
      label: 'Breads (Assorted)',
      emoji: '🫓',
      items: [
        { name: 'Butter Naan' },
        { name: 'Tandoori Roti' },
        { name: 'Laccha Paratha' },
        { name: 'Missi Roti' },
        { name: 'Kulcha' },
        { name: 'Garlic Naan' },
      ],
    },
    {
      id: 'desserts',
      label: 'Desserts',
      emoji: '🍮',
      limit: 5,
      items: [
        { name: 'Gulab Jamun' },
        { name: 'Rasgulla' },
        { name: 'Kheer' },
        { name: 'Gajar Halwa' },
        { name: 'Moong Dal Halwa' },
        { name: 'Phirni' },
        { name: 'Jalebi with Rabri' },
        { name: 'Ras Malai' },
        { name: 'Kulfi Falooda' },
        { name: 'Shahi Tukda' },
      ],
    },
  ],
  liveStations: [
    {
      id: 'tawa',
      label: 'Tawa Tak-A-Tak Station',
      subItems: ['Tawa Paneer', 'Tawa Aloo', 'Tawa Mushroom', 'Tawa Gobhi'],
    },
    {
      id: 'chaat',
      label: 'Chaat Corner',
      subItems: ['Pani Puri', 'Sev Puri', 'Bhel Puri', 'Dahi Bhalla', 'Raj Kachori'],
    },
    {
      id: 'pasta',
      label: 'Live Pasta Station',
      subItems: ['Penne Arrabbiata', 'Mac & Cheese', 'Spaghetti Aglio e Olio'],
    },
    {
      id: 'ice-cream',
      label: 'Ice Cream Counter',
      subItems: ['Vanilla', 'Chocolate', 'Strawberry', 'Butterscotch', 'Mango', 'Pista'],
    },
  ],
  addOns: PDF_ADDONS,
}

export const VEG_PLATINUM: BanquetPackage = {
  id: 'veg-platinum',
  name: 'Platinum Veg Banquet',
  mealType: 'veg',
  pricePerHead: 3000,
  tagline: '₹3,000 per head · The ultimate royal vegetarian celebration',
  categories: [
    {
      id: 'welcome-drinks',
      label: 'Welcome Drinks',
      emoji: '🥤',
      limit: 4,
      items: [
        { name: 'Mango Lassi' },
        { name: 'Rose Sherbat' },
        { name: 'Lemon Mint Cooler' },
        { name: 'Jaljeera' },
        { name: 'Aam Panna' },
        { name: 'Thandai' },
        { name: 'Masala Chach (Buttermilk)' },
        { name: 'Coconut Water' },
        { name: 'Fresh Lime Soda' },
        { name: 'Blue Lagoon Mocktail' },
        { name: 'Virgin Mojito' },
      ],
    },
    {
      id: 'starters-veg-indian',
      label: 'Starters — Veg Indian',
      emoji: '🥗',
      limit: 6,
      items: [
        ...VEG_STARTERS_INDIAN_REGULAR,
        ...VEG_STARTERS_INDIAN_PREMIUM,
        ...VEG_STARTERS_INDIAN_SUPER_PREMIUM,
      ],
    },
    {
      id: 'starters-veg-oriental',
      label: 'Starters — Veg Oriental & Western',
      emoji: '🥡',
      limit: 4,
      items: [
        ...VEG_STARTERS_ORIENTAL_REGULAR,
        ...VEG_STARTERS_ORIENTAL_PREMIUM,
        ...VEG_STARTERS_ORIENTAL_SUPER_PREMIUM,
      ],
    },
    {
      id: 'soup',
      label: 'Soup',
      emoji: '🍲',
      limit: 3,
      items: [
        { name: 'Tomato Shorba' },
        { name: 'Sweet Corn Vegetable Soup' },
        { name: 'Dal Shorba' },
        { name: 'Mulligatawny Soup (Veg)' },
        { name: 'Mushroom Cream Soup' },
        { name: 'Hot & Sour Vegetable Soup' },
        { name: 'Lemon Coriander Soup' },
        { name: 'Manchow Soup' },
      ],
    },
    {
      id: 'salads',
      label: 'Salads',
      emoji: '🥙',
      limit: 6,
      items: [
        { name: 'Green Salad' },
        { name: 'Russian Salad' },
        { name: 'Sprouts Salad' },
        { name: 'Corn Salad' },
        { name: 'Pasta Salad' },
        { name: 'Coleslaw' },
        { name: 'Fruit Salad' },
        { name: 'Papdi Chaat' },
        { name: 'Greek Salad' },
        { name: 'Thai Salad' },
        { name: 'Waldorf Salad' },
      ],
    },
    {
      id: 'raita-curd',
      label: 'Raita / Curd',
      emoji: '🫙',
      limit: 2,
      items: [
        { name: 'Boondi Raita' },
        { name: 'Mixed Raita' },
        { name: 'Cucumber Raita' },
        { name: 'Plain Curd' },
        { name: 'Pineapple Raita' },
        { name: 'Fruit Raita' },
      ],
    },
    {
      id: 'paneer-main',
      label: 'Paneer Main Course',
      emoji: '🧀',
      limit: 3,
      items: [
        { name: 'Paneer Butter Masala' },
        { name: 'Shahi Paneer' },
        { name: 'Kadai Paneer' },
        { name: 'Palak Paneer' },
        { name: 'Paneer Lababdar' },
        { name: 'Paneer Makhani' },
        { name: 'Paneer Pasanda' },
        { name: 'Paneer Tikka Masala' },
      ],
    },
    {
      id: 'veg-main',
      label: 'Veg Main Course',
      emoji: '🍛',
      limit: 5,
      items: [
        { name: 'Aloo Gobi' },
        { name: 'Veg Kolhapuri' },
        { name: 'Matar Mushroom' },
        { name: 'Bhindi Masala' },
        { name: 'Lauki Kofta' },
        { name: 'Mix Vegetable' },
        { name: 'Dum Aloo' },
        { name: 'Navratan Korma' },
        { name: 'Tindora Masala' },
        { name: 'Veg Jaipuri' },
        { name: 'Kaju Curry' },
      ],
    },
    {
      id: 'dal',
      label: 'Dal',
      emoji: '🫕',
      limit: 2,
      items: [
        { name: 'Dal Makhani' },
        { name: 'Dal Tadka' },
        { name: 'Dal Fry' },
        { name: 'Panchmel Dal' },
        { name: 'Chana Masala' },
        { name: 'Rajma Masala' },
        { name: 'Dal Maharani' },
      ],
    },
    {
      id: 'rice-noodles',
      label: 'Rice / Noodles',
      emoji: '🍚',
      limit: 3,
      items: [
        { name: 'Steamed Rice' },
        { name: 'Jeera Rice' },
        { name: 'Veg Pulao' },
        { name: 'Veg Biryani' },
        { name: 'Schezwan Fried Rice' },
        { name: 'Veg Hakka Noodles' },
        { name: 'Kashmiri Pulao' },
        { name: 'Hyderabadi Veg Biryani' },
      ],
    },
    {
      id: 'breads',
      label: 'Breads (Assorted)',
      emoji: '🫓',
      items: [
        { name: 'Butter Naan' },
        { name: 'Tandoori Roti' },
        { name: 'Laccha Paratha' },
        { name: 'Missi Roti' },
        { name: 'Kulcha' },
        { name: 'Garlic Naan' },
        { name: 'Pudina Paratha' },
      ],
    },
    {
      id: 'desserts',
      label: 'Desserts',
      emoji: '🍮',
      limit: 6,
      items: [
        { name: 'Gulab Jamun' },
        { name: 'Rasgulla' },
        { name: 'Kheer' },
        { name: 'Gajar Halwa' },
        { name: 'Moong Dal Halwa' },
        { name: 'Phirni' },
        { name: 'Jalebi with Rabri' },
        { name: 'Ras Malai' },
        { name: 'Kulfi Falooda' },
        { name: 'Shahi Tukda' },
        { name: 'Baklava' },
      ],
    },
  ],
  liveStations: [
    {
      id: 'tawa',
      label: 'Tawa Tak-A-Tak Station',
      subItems: ['Tawa Paneer', 'Tawa Aloo', 'Tawa Mushroom', 'Tawa Gobhi'],
    },
    {
      id: 'chaat',
      label: 'Chaat Corner',
      subItems: ['Pani Puri', 'Sev Puri', 'Bhel Puri', 'Dahi Bhalla', 'Raj Kachori'],
    },
    {
      id: 'pasta',
      label: 'Pasta & Pizza Station',
      subItems: ['Penne Arrabbiata', 'Mac & Cheese', 'Spaghetti Aglio e Olio'],
    },
    {
      id: 'indian-sweets',
      label: 'Live Indian Sweets Counter',
      subItems: ['Jalebi (freshly fried)', 'Gulab Jamun (warm)', 'Malpua'],
    },
    {
      id: 'ice-cream',
      label: 'Ice Cream & Dessert Counter',
      subItems: ['Vanilla', 'Chocolate', 'Strawberry', 'Butterscotch', 'Mango', 'Pista', 'Kulfi (Malai)'],
    },
  ],
  addOns: PDF_ADDONS,
}

// ──────────────────────────────────────────────────────
// NON-VEGETARIAN BANQUET PACKAGES
// ──────────────────────────────────────────────────────

export const NON_VEG_PREMIUM: BanquetPackage = {
  id: 'non-veg-premium',
  name: 'Premium Non-Veg Banquet',
  mealType: 'non-veg',
  pricePerHead: 2650,
  tagline: '₹2,650 per head · A rich non-vegetarian banquet experience',
  categories: [
    {
      id: 'welcome-drinks',
      label: 'Welcome Drinks',
      emoji: '🥤',
      limit: 2,
      items: [
        { name: 'Mango Lassi' },
        { name: 'Rose Sherbat' },
        { name: 'Lemon Mint Cooler' },
        { name: 'Jaljeera' },
        { name: 'Aam Panna' },
        { name: 'Masala Chach (Buttermilk)' },
        { name: 'Coconut Water' },
      ],
    },
    {
      id: 'starters-nonveg-indian',
      label: 'Starters — Non-Veg Indian',
      emoji: '🍗',
      limit: 4,
      items: [...NON_VEG_STARTERS_INDIAN_REGULAR, ...NON_VEG_STARTERS_INDIAN_PREMIUM],
    },
    {
      id: 'starters-nonveg-oriental',
      label: 'Starters — Non-Veg Oriental & Western',
      emoji: '🥡',
      limit: 2,
      items: [...NON_VEG_STARTERS_ORIENTAL_REGULAR, ...NON_VEG_STARTERS_ORIENTAL_PREMIUM],
    },
    {
      id: 'soup',
      label: 'Soup',
      emoji: '🍲',
      limit: 2,
      items: [
        { name: 'Chicken Shorba' },
        { name: 'Tomato Shorba' },
        { name: 'Mulligatawny Soup' },
        { name: 'Sweet Corn Chicken Soup' },
        { name: 'Hot & Sour Chicken Soup' },
        { name: 'Mutton Nihari Soup' },
      ],
    },
    {
      id: 'salads',
      label: 'Salads',
      emoji: '🥙',
      limit: 4,
      items: [
        { name: 'Green Salad' },
        { name: 'Russian Salad' },
        { name: 'Chicken Caesar Salad' },
        { name: 'Coleslaw' },
        { name: 'Fruit Salad' },
        { name: 'Pasta Salad' },
      ],
    },
    {
      id: 'nonveg-main',
      label: 'Non-Veg Main Course',
      emoji: '🍖',
      limit: 2,
      items: [
        { name: 'Butter Chicken' },
        { name: 'Chicken Curry' },
        { name: 'Chicken Korma' },
        { name: 'Mutton Rogan Josh' },
        { name: 'Mutton Curry' },
        { name: 'Kadai Chicken' },
      ],
    },
    {
      id: 'veg-main',
      label: 'Veg Main Course',
      emoji: '🍛',
      limit: 2,
      items: [
        { name: 'Paneer Butter Masala' },
        { name: 'Kadai Paneer' },
        { name: 'Mix Vegetable' },
        { name: 'Aloo Gobi' },
      ],
    },
    {
      id: 'dal',
      label: 'Dal',
      emoji: '🫕',
      limit: 1,
      items: [
        { name: 'Dal Makhani' },
        { name: 'Dal Tadka' },
      ],
    },
    {
      id: 'rice-biryani',
      label: 'Rice / Biryani',
      emoji: '🍚',
      limit: 2,
      items: [
        { name: 'Chicken Dum Biryani' },
        { name: 'Jeera Rice' },
        { name: 'Steamed Rice' },
        { name: 'Mutton Biryani' },
      ],
    },
    {
      id: 'breads',
      label: 'Breads (Assorted)',
      emoji: '🫓',
      items: [
        { name: 'Butter Naan' },
        { name: 'Tandoori Roti' },
        { name: 'Laccha Paratha' },
      ],
    },
    {
      id: 'desserts',
      label: 'Desserts',
      emoji: '🍮',
      limit: 4,
      items: [
        { name: 'Gulab Jamun' },
        { name: 'Ras Malai' },
        { name: 'Gajar Halwa' },
        { name: 'Phirni' },
        { name: 'Ice Cream (Vanilla / Chocolate)' },
      ],
    },
  ],
  liveStations: [
    {
      id: 'tawa-nonveg',
      label: 'Live Non-Veg Tawa Station',
      subItems: ['Tawa Chicken', 'Tawa Seekh', 'Fish Fry'],
    },
    {
      id: 'ice-cream',
      label: 'Ice Cream Counter',
      subItems: ['Vanilla', 'Chocolate', 'Strawberry'],
    },
  ],
  addOns: PDF_ADDONS,
}

export const NON_VEG_EXECUTIVE: BanquetPackage = {
  id: 'non-veg-executive',
  name: 'Executive Non-Veg Banquet',
  mealType: 'non-veg',
  pricePerHead: 3150,
  tagline: '₹3,150 per head · A premium non-vegetarian feast with extra variety',
  categories: [
    {
      id: 'welcome-drinks',
      label: 'Welcome Drinks',
      emoji: '🥤',
      limit: 3,
      items: [
        { name: 'Mango Lassi' },
        { name: 'Rose Sherbat' },
        { name: 'Lemon Mint Cooler' },
        { name: 'Jaljeera' },
        { name: 'Aam Panna' },
        { name: 'Coconut Water' },
        { name: 'Fresh Lime Soda' },
      ],
    },
    {
      id: 'starters-nonveg-indian',
      label: 'Starters — Non-Veg Indian',
      emoji: '🍗',
      limit: 5,
      items: [...NON_VEG_STARTERS_INDIAN_PREMIUM, ...NON_VEG_STARTERS_INDIAN_SUPER_PREMIUM],
    },
    {
      id: 'starters-nonveg-oriental',
      label: 'Starters — Non-Veg Oriental & Western',
      emoji: '🥡',
      limit: 3,
      items: [...NON_VEG_STARTERS_ORIENTAL_PREMIUM],
    },
    {
      id: 'soup',
      label: 'Soup',
      emoji: '🍲',
      limit: 2,
      items: [
        { name: 'Chicken Shorba' },
        { name: 'Tomato Shorba' },
        { name: 'Sweet Corn Chicken Soup' },
        { name: 'Hot & Sour Chicken Soup' },
        { name: 'Mutton Nihari Soup' },
      ],
    },
    {
      id: 'salads',
      label: 'Salads',
      emoji: '🥙',
      limit: 5,
      items: [
        { name: 'Green Salad' },
        { name: 'Russian Salad' },
        { name: 'Chicken Caesar Salad' },
        { name: 'Coleslaw' },
        { name: 'Fruit Salad' },
        { name: 'Pasta Salad' },
        { name: 'Greek Salad' },
      ],
    },
    {
      id: 'nonveg-main',
      label: 'Non-Veg Main Course',
      emoji: '🍖',
      limit: 3,
      items: [
        { name: 'Butter Chicken' },
        { name: 'Chicken Lababdar' },
        { name: 'Mutton Rogan Josh' },
        { name: 'Mutton Korma' },
        { name: 'Fish Curry' },
        { name: 'Chicken Tikka Masala' },
      ],
    },
    {
      id: 'veg-main',
      label: 'Veg Main Course',
      emoji: '🍛',
      limit: 3,
      items: [
        { name: 'Paneer Butter Masala' },
        { name: 'Shahi Paneer' },
        { name: 'Mix Vegetable' },
        { name: 'Matar Mushroom' },
      ],
    },
    {
      id: 'dal',
      label: 'Dal',
      emoji: '🫕',
      limit: 1,
      items: [
        { name: 'Dal Makhani' },
        { name: 'Dal Tadka' },
      ],
    },
    {
      id: 'rice-biryani',
      label: 'Rice / Biryani',
      emoji: '🍚',
      limit: 2,
      items: [
        { name: 'Chicken Dum Biryani' },
        { name: 'Mutton Dum Biryani' },
        { name: 'Jeera Rice' },
        { name: 'Steamed Rice' },
      ],
    },
    {
      id: 'breads',
      label: 'Breads (Assorted)',
      emoji: '🫓',
      items: [
        { name: 'Butter Naan' },
        { name: 'Tandoori Roti' },
        { name: 'Laccha Paratha' },
        { name: 'Garlic Naan' },
      ],
    },
    {
      id: 'desserts',
      label: 'Desserts',
      emoji: '🍮',
      limit: 5,
      items: [
        { name: 'Gulab Jamun' },
        { name: 'Ras Malai' },
        { name: 'Gajar Halwa' },
        { name: 'Phirni' },
        { name: 'Jalebi with Rabri' },
        { name: 'Shahi Tukda' },
      ],
    },
  ],
  liveStations: [
    {
      id: 'tawa-nonveg',
      label: 'Live Non-Veg Tawa Station',
      subItems: ['Tawa Chicken', 'Tawa Seekh', 'Fish Fry', 'Mutton Boti'],
    },
    {
      id: 'pasta',
      label: 'Live Pasta Station (Veg & Chicken)',
      subItems: ['Penne Arrabbiata', 'Chicken Alfredo Pasta'],
    },
    {
      id: 'ice-cream',
      label: 'Ice Cream Counter',
      subItems: ['Vanilla', 'Chocolate', 'Strawberry', 'Butterscotch', 'Mango'],
    },
  ],
  addOns: PDF_ADDONS,
}

export const NON_VEG_PLATINUM: BanquetPackage = {
  id: 'non-veg-platinum',
  name: 'Platinum Non-Veg Banquet',
  mealType: 'non-veg',
  pricePerHead: 3650,
  tagline: '₹3,650 per head · The ultimate royal non-vegetarian feast',
  categories: [
    {
      id: 'welcome-drinks',
      label: 'Welcome Drinks',
      emoji: '🥤',
      limit: 4,
      items: [
        { name: 'Mango Lassi' },
        { name: 'Rose Sherbat' },
        { name: 'Lemon Mint Cooler' },
        { name: 'Jaljeera' },
        { name: 'Aam Panna' },
        { name: 'Coconut Water' },
        { name: 'Fresh Lime Soda' },
        { name: 'Virgin Mojito' },
        { name: 'Blue Lagoon Mocktail' },
      ],
    },
    {
      id: 'starters-nonveg-indian',
      label: 'Starters — Non-Veg Indian',
      emoji: '🍗',
      limit: 6,
      items: [
        ...NON_VEG_STARTERS_INDIAN_REGULAR,
        ...NON_VEG_STARTERS_INDIAN_PREMIUM,
        ...NON_VEG_STARTERS_INDIAN_SUPER_PREMIUM,
      ],
    },
    {
      id: 'starters-nonveg-oriental',
      label: 'Starters — Non-Veg Oriental & Western',
      emoji: '🥡',
      limit: 4,
      items: [
        ...NON_VEG_STARTERS_ORIENTAL_REGULAR,
        ...NON_VEG_STARTERS_ORIENTAL_PREMIUM,
      ],
    },
    {
      id: 'starters-prawn-special',
      label: 'Starters — Prawn Special',
      emoji: '🍤',
      limit: 2,
      items: PRAWN_STARTERS,
    },
    {
      id: 'soup',
      label: 'Soup',
      emoji: '🍲',
      limit: 3,
      items: [
        { name: 'Chicken Shorba' },
        { name: 'Tomato Shorba' },
        { name: 'Sweet Corn Chicken Soup' },
        { name: 'Hot & Sour Chicken Soup' },
        { name: 'Mutton Nihari Soup' },
        { name: 'Seafood Soup' },
      ],
    },
    {
      id: 'salads',
      label: 'Salads',
      emoji: '🥙',
      limit: 6,
      items: [
        { name: 'Green Salad' },
        { name: 'Russian Salad' },
        { name: 'Chicken Caesar Salad' },
        { name: 'Coleslaw' },
        { name: 'Fruit Salad' },
        { name: 'Pasta Salad' },
        { name: 'Greek Salad' },
        { name: 'Waldorf Salad' },
      ],
    },
    {
      id: 'nonveg-main',
      label: 'Non-Veg Main Course',
      emoji: '🍖',
      limit: 4,
      items: [
        { name: 'Butter Chicken' },
        { name: 'Chicken Lababdar' },
        { name: 'Mutton Rogan Josh' },
        { name: 'Mutton Raan Masala' },
        { name: 'Fish Curry (Sole)' },
        { name: 'Kadhai Jhinga (Prawn Main)' },
        { name: 'Chicken Tikka Masala' },
      ],
    },
    {
      id: 'veg-main',
      label: 'Veg Main Course',
      emoji: '🍛',
      limit: 3,
      items: [
        { name: 'Paneer Butter Masala' },
        { name: 'Shahi Paneer' },
        { name: 'Mix Vegetable' },
        { name: 'Matar Mushroom' },
        { name: 'Kaju Curry' },
      ],
    },
    {
      id: 'dal',
      label: 'Dal',
      emoji: '🫕',
      limit: 2,
      items: [
        { name: 'Dal Makhani' },
        { name: 'Dal Tadka' },
        { name: 'Panchmel Dal' },
      ],
    },
    {
      id: 'rice-biryani',
      label: 'Rice / Biryani',
      emoji: '🍚',
      limit: 3,
      items: [
        { name: 'Chicken Dum Biryani' },
        { name: 'Mutton Dum Biryani' },
        { name: 'Hyderabadi Biryani' },
        { name: 'Jeera Rice' },
        { name: 'Steamed Rice' },
      ],
    },
    {
      id: 'breads',
      label: 'Breads (Assorted)',
      emoji: '🫓',
      items: [
        { name: 'Butter Naan' },
        { name: 'Tandoori Roti' },
        { name: 'Laccha Paratha' },
        { name: 'Garlic Naan' },
        { name: 'Pudina Paratha' },
      ],
    },
    {
      id: 'desserts',
      label: 'Desserts',
      emoji: '🍮',
      limit: 6,
      items: [
        { name: 'Gulab Jamun' },
        { name: 'Ras Malai' },
        { name: 'Gajar Halwa' },
        { name: 'Phirni' },
        { name: 'Jalebi with Rabri' },
        { name: 'Shahi Tukda' },
        { name: 'Baklava' },
        { name: 'Kulfi Falooda' },
      ],
    },
  ],
  liveStations: [
    {
      id: 'tawa-nonveg',
      label: 'Live Non-Veg Tawa Station',
      subItems: ['Tawa Chicken', 'Tawa Seekh', 'Fish Fry', 'Mutton Boti', 'Tawa Prawns'],
    },
    {
      id: 'pasta',
      label: 'Pasta & Pizza Station (Live)',
      subItems: ['Penne Arrabbiata', 'Chicken Alfredo Pasta', 'Chicken Pizza'],
    },
    {
      id: 'indian-sweets',
      label: 'Live Indian Sweets Counter',
      subItems: ['Jalebi (freshly fried)', 'Gulab Jamun (warm)', 'Malpua'],
    },
    {
      id: 'ice-cream',
      label: 'Ice Cream & Dessert Counter',
      subItems: ['Vanilla', 'Chocolate', 'Strawberry', 'Butterscotch', 'Mango', 'Pista', 'Kulfi (Malai)'],
    },
  ],
  addOns: PDF_ADDONS,
}

// ──────────────────────────────────────────────────────
// Helpers
// ──────────────────────────────────────────────────────

export const ALL_BANQUET_PACKAGES: BanquetPackage[] = [
  VEG_PREMIUM,
  VEG_EXECUTIVE,
  VEG_PLATINUM,
  NON_VEG_PREMIUM,
  NON_VEG_EXECUTIVE,
  NON_VEG_PLATINUM,
]

/** Return the banquet packages matching a given food preference. */
export function getPackagesForMealType(mealType: 'veg' | 'non-veg'): BanquetPackage[] {
  return ALL_BANQUET_PACKAGES.filter((p) => p.mealType === mealType)
}

/** Find a package by ID. */
export function findPackageById(id: string): BanquetPackage | undefined {
  return ALL_BANQUET_PACKAGES.find((p) => p.id === id)
}
